require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot
  - rubocop-rspec_rails
AllCops:
  NewCops: enable
  Exclude:
    - projects/**/*
    - bin/**/*
    - db/schema.rb
    - spec/spec_helper.rb
    - spec/rails_helper.rb
    - spec/factories/**/*
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
  Max: 30
Layout/LineLength:
  Max: 150
Naming/VariableNumber:
  EnforcedStyle: snake_case
RSpec/ExampleLength:
  Max: 15
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/NestedGroups:
  Max: 6
Metrics/ClassLength:
  Max: 300
Metrics/BlockLength:
  Max: 30
